// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectE__SENAI.Context;

#nullable disable

namespace ProjectE__SENAI.Migrations
{
    [DbContext(typeof(ProjectE_Context))]
    partial class ProjectE_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectE__SENAI.Domains.Evento", b =>
                {
                    b.Property<Guid>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("DATETIME");

                    b.Property<Guid?>("IdInstituicao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPresenca")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTiposEventos")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("IdEvento");

                    b.HasIndex("IdInstituicao");

                    b.HasIndex("IdPresenca");

                    b.HasIndex("IdTiposEventos");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("ProjectE__SENAI.Domains.Feedback", b =>
                {
                    b.Property<Guid>("IdFeedback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("VARCHAR(120)");

                    b.Property<Guid?>("EventoIdEvento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEvento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdInstituicao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocalIdInstituição")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioIdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdFeedback");

                    b.HasIndex("EventoIdEvento");

                    b.HasIndex("LocalIdInstituição");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("ProjectE__SENAI.Domains.Instituicao", b =>
                {
                    b.Property<Guid>("IdInstituição")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("CHAR(14)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Vestimenta")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("IdInstituição");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.ToTable("Instituicao");
                });

            modelBuilder.Entity("ProjectE__SENAI.Domains.Presenca", b =>
                {
                    b.Property<Guid>("IdPresenca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Exibe")
                        .IsRequired()
                        .HasColumnType("VARCHAR(120)");

                    b.Property<Guid?>("IdEvento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("comentário")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPresenca");

                    b.HasIndex("IdEvento");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Presença");
                });

            modelBuilder.Entity("ProjectE__SENAI.Domains.TiposEventos", b =>
                {
                    b.Property<Guid>("IdTiposEventos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TituloTiposEventos")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("IdTiposEventos");

                    b.ToTable("TiposEventos");
                });

            modelBuilder.Entity("ProjectE__SENAI.Domains.TiposUsuarios", b =>
                {
                    b.Property<Guid>("IdTiposUsuarios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TituloTiposUsuarios")
                        .IsRequired()
                        .HasColumnType("Char(100)");

                    b.HasKey("IdTiposUsuarios");

                    b.ToTable("TiposUsuarios");
                });

            modelBuilder.Entity("ProjectE__SENAI.Domains.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<Guid>("IdTipoUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<Guid?>("TiposUsuarios")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TiposUsuarios");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ProjectE__SENAI.Domains.Evento", b =>
                {
                    b.HasOne("ProjectE__SENAI.Domains.Instituicao", "Local")
                        .WithMany()
                        .HasForeignKey("IdInstituicao");

                    b.HasOne("ProjectE__SENAI.Domains.Presenca", "Presenca")
                        .WithMany()
                        .HasForeignKey("IdPresenca");

                    b.HasOne("ProjectE__SENAI.Domains.TiposEventos", "TiposEventos")
                        .WithMany()
                        .HasForeignKey("IdTiposEventos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Presenca");

                    b.Navigation("TiposEventos");
                });

            modelBuilder.Entity("ProjectE__SENAI.Domains.Feedback", b =>
                {
                    b.HasOne("ProjectE__SENAI.Domains.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoIdEvento");

                    b.HasOne("ProjectE__SENAI.Domains.Instituicao", "Local")
                        .WithMany()
                        .HasForeignKey("LocalIdInstituição");

                    b.HasOne("ProjectE__SENAI.Domains.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Evento");

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjectE__SENAI.Domains.Presenca", b =>
                {
                    b.HasOne("ProjectE__SENAI.Domains.Instituicao", "Local")
                        .WithMany()
                        .HasForeignKey("IdEvento");

                    b.HasOne("ProjectE__SENAI.Domains.Evento", "evento")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("evento");
                });

            modelBuilder.Entity("ProjectE__SENAI.Domains.Usuario", b =>
                {
                    b.HasOne("ProjectE__SENAI.Domains.TiposUsuarios", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("TiposUsuarios");

                    b.Navigation("TipoUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
